[tool.kedro]
package_name = "dynamic_pipeline"
project_name = "dynamic_pipeline"
kedro_init_version = "0.18.11"

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = """
--cov-report term-missing \
--cov src/dynamic_pipeline -ra"""

[tool.coverage.report]
fail_under = 0
show_missing = true
exclude_lines = ["pragma: no cover", "raise NotImplementedError"]
