[tool.kedro]
package_name = "omegaconfigloader_demo"
project_name = "omegaconfigloader_demo"
project_version = "0.18.5"

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = """
--cov-report term-missing \
--cov src/omegaconfigloader_demo -ra"""

[tool.coverage.report]
fail_under = 0
show_missing = true
exclude_lines = ["pragma: no cover", "raise NotImplementedError"]
