[tool.kedro]
package_name = "kedro_debug_runner_demo"
project_name = "kedro_debug_runner_demo"
project_version = "0.0.1"

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = """
--cov-report term-missing \
--cov src/kedro_debug_runner_demo -ra"""

[tool.coverage.report]
fail_under = 0
show_missing = true
exclude_lines = ["pragma: no cover", "raise NotImplementedError"]
